CREATE DATABASE IF NOT EXISTS smartvision_crm DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE smartvision_crm;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(160) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('admin','staff') NOT NULL DEFAULT 'staff',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  must_change_password TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS countries (
  id INT AUTO_INCREMENT PRIMARY KEY,
  iso2 CHAR(2) NOT NULL UNIQUE,
  name VARCHAR(150) NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 0,
  INDEX(name),
  INDEX(is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS events (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(180) NOT NULL,
  event_date_from DATE NULL,
  event_date_to DATE NULL,
  location VARCHAR(180) NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_event_name (name),
  INDEX idx_events_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS lost_categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_lost_cat (name),
  INDEX idx_lost_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS packages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL UNIQUE,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS leads (
  id INT AUTO_INCREMENT PRIMARY KEY,
  company_name VARCHAR(255) NOT NULL,
  contact_person VARCHAR(120) NULL,
  contact_mobile VARCHAR(50) NULL,
  contact_email VARCHAR(160) NULL,
  contact_linkedin VARCHAR(255) NULL,
  company_website VARCHAR(255) NULL,
  event_id INT NULL,
  interested_package_id INT NULL,
  expected_value DECIMAL(12,2) NULL,
  currency CHAR(3) NOT NULL DEFAULT 'USD',
  probability TINYINT NULL,
  expected_close_date DATE NULL,
  lead_notes TEXT NULL,
  status ENUM('new','contacted','meeting','negotiation','won','lost') NOT NULL DEFAULT 'new',
  lost_category_id INT NULL,
  lost_reason VARCHAR(255) NULL,
  lost_at TIMESTAMP NULL,
  sales_rep_id INT NULL,
  last_meeting DATE NULL,
  next_followup DATE NULL,
  created_by INT NULL,
  updated_by INT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,

  INDEX idx_sales_rep (sales_rep_id),
  INDEX idx_followup (next_followup),
  INDEX idx_event (event_id),
  INDEX idx_status (status),
  INDEX idx_lost_cat (lost_category_id),
  INDEX idx_created_at (created_at),
  INDEX idx_company_name (company_name),

  CONSTRAINT fk_leads_pkg FOREIGN KEY (interested_package_id) REFERENCES packages(id) ON DELETE SET NULL,
  CONSTRAINT fk_leads_lost_cat FOREIGN KEY (lost_category_id) REFERENCES lost_categories(id) ON DELETE SET NULL,
  CONSTRAINT fk_leads_rep FOREIGN KEY (sales_rep_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_leads_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_leads_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS lead_countries (
  lead_id INT NOT NULL,
  country_id INT NOT NULL,
  PRIMARY KEY (lead_id, country_id),
  CONSTRAINT fk_lc_lead FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE,
  CONSTRAINT fk_lc_country FOREIGN KEY (country_id) REFERENCES countries(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS meetings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  lead_id INT NULL,
  meeting_date DATE NOT NULL,
  duration_minutes INT NOT NULL DEFAULT 0,
  meeting_type ENUM('call','online','in_person') NOT NULL DEFAULT 'call',
  notes VARCHAR(255) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_meetings_user (user_id),
  INDEX idx_meetings_date (meeting_date),
  CONSTRAINT fk_meetings_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_meetings_lead FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS lead_activities (
  id INT AUTO_INCREMENT PRIMARY KEY,
  lead_id INT NOT NULL,
  user_id INT NULL,
  activity_type ENUM('create','update','status_change','meeting','note','import') NOT NULL,
  message VARCHAR(255) NULL,
  meta JSON NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_act_lead (lead_id),
  INDEX idx_act_date (created_at),
  CONSTRAINT fk_act_lead FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE CASCADE,
  CONSTRAINT fk_act_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS audit_log (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NULL,
  action VARCHAR(60) NOT NULL,
  entity VARCHAR(40) NOT NULL,
  entity_id INT NULL,
  meta JSON NULL,
  ip VARCHAR(64) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_user (user_id),
  INDEX idx_action (action),
  CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Seed all countries (ISO 3166-1)
INSERT INTO countries (iso2,name,is_active,sort_order) VALUES
  ('AF','Afghanistan',1,1),
  ('AL','Albania',1,2),
  ('DZ','Algeria',1,3),
  ('AS','American Samoa',1,4),
  ('AD','Andorra',1,5),
  ('AO','Angola',1,6),
  ('AI','Anguilla',1,7),
  ('AQ','Antarctica',1,8),
  ('AG','Antigua and Barbuda',1,9),
  ('AR','Argentina',1,10),
  ('AM','Armenia',1,11),
  ('AW','Aruba',1,12),
  ('AU','Australia',1,13),
  ('AT','Austria',1,14),
  ('AZ','Azerbaijan',1,15),
  ('BS','Bahamas',1,16),
  ('BH','Bahrain',1,17),
  ('BD','Bangladesh',1,18),
  ('BB','Barbados',1,19),
  ('BY','Belarus',1,20),
  ('BE','Belgium',1,21),
  ('BZ','Belize',1,22),
  ('BJ','Benin',1,23),
  ('BM','Bermuda',1,24),
  ('BT','Bhutan',1,25),
  ('BO','Bolivia, Plurinational State of',1,26),
  ('BQ','Bonaire, Sint Eustatius and Saba',1,27),
  ('BA','Bosnia and Herzegovina',1,28),
  ('BW','Botswana',1,29),
  ('BV','Bouvet Island',1,30),
  ('BR','Brazil',1,31),
  ('IO','British Indian Ocean Territory',1,32),
  ('BN','Brunei Darussalam',1,33),
  ('BG','Bulgaria',1,34),
  ('BF','Burkina Faso',1,35),
  ('BI','Burundi',1,36),
  ('CV','Cabo Verde',1,37),
  ('KH','Cambodia',1,38),
  ('CM','Cameroon',1,39),
  ('CA','Canada',1,40),
  ('KY','Cayman Islands',1,41),
  ('CF','Central African Republic',1,42),
  ('TD','Chad',1,43),
  ('CL','Chile',1,44),
  ('CN','China',1,45),
  ('CX','Christmas Island',1,46),
  ('CC','Cocos (Keeling) Islands',1,47),
  ('CO','Colombia',1,48),
  ('KM','Comoros',1,49),
  ('CG','Congo',1,50),
  ('CD','Congo, The Democratic Republic of the',1,51),
  ('CK','Cook Islands',1,52),
  ('CR','Costa Rica',1,53),
  ('HR','Croatia',1,54),
  ('CU','Cuba',1,55),
  ('CW','Curaçao',1,56),
  ('CY','Cyprus',1,57),
  ('CZ','Czechia',1,58),
  ('CI','Côte d''Ivoire',1,59),
  ('DK','Denmark',1,60),
  ('DJ','Djibouti',1,61),
  ('DM','Dominica',1,62),
  ('DO','Dominican Republic',1,63),
  ('EC','Ecuador',1,64),
  ('EG','Egypt',1,65),
  ('SV','El Salvador',1,66),
  ('GQ','Equatorial Guinea',1,67),
  ('ER','Eritrea',1,68),
  ('EE','Estonia',1,69),
  ('SZ','Eswatini',1,70),
  ('ET','Ethiopia',1,71),
  ('FK','Falkland Islands (Malvinas)',1,72),
  ('FO','Faroe Islands',1,73),
  ('FJ','Fiji',1,74),
  ('FI','Finland',1,75),
  ('FR','France',1,76),
  ('GF','French Guiana',1,77),
  ('PF','French Polynesia',1,78),
  ('TF','French Southern Territories',1,79),
  ('GA','Gabon',1,80),
  ('GM','Gambia',1,81),
  ('GE','Georgia',1,82),
  ('DE','Germany',1,83),
  ('GH','Ghana',1,84),
  ('GI','Gibraltar',1,85),
  ('GR','Greece',1,86),
  ('GL','Greenland',1,87),
  ('GD','Grenada',1,88),
  ('GP','Guadeloupe',1,89),
  ('GU','Guam',1,90),
  ('GT','Guatemala',1,91),
  ('GG','Guernsey',1,92),
  ('GN','Guinea',1,93),
  ('GW','Guinea-Bissau',1,94),
  ('GY','Guyana',1,95),
  ('HT','Haiti',1,96),
  ('HM','Heard Island and McDonald Islands',1,97),
  ('VA','Holy See (Vatican City State)',1,98),
  ('HN','Honduras',1,99),
  ('HK','Hong Kong',1,100),
  ('HU','Hungary',1,101),
  ('IS','Iceland',1,102),
  ('IN','India',1,103),
  ('ID','Indonesia',1,104),
  ('IR','Iran, Islamic Republic of',1,105),
  ('IQ','Iraq',1,106),
  ('IE','Ireland',1,107),
  ('IM','Isle of Man',1,108),
  ('IL','Israel',1,109),
  ('IT','Italy',1,110),
  ('JM','Jamaica',1,111),
  ('JP','Japan',1,112),
  ('JE','Jersey',1,113),
  ('JO','Jordan',1,114),
  ('KZ','Kazakhstan',1,115),
  ('KE','Kenya',1,116),
  ('KI','Kiribati',1,117),
  ('KP','Korea, Democratic People''s Republic of',1,118),
  ('KR','Korea, Republic of',1,119),
  ('KW','Kuwait',1,120),
  ('KG','Kyrgyzstan',1,121),
  ('LA','Lao People''s Democratic Republic',1,122),
  ('LV','Latvia',1,123),
  ('LB','Lebanon',1,124),
  ('LS','Lesotho',1,125),
  ('LR','Liberia',1,126),
  ('LY','Libya',1,127),
  ('LI','Liechtenstein',1,128),
  ('LT','Lithuania',1,129),
  ('LU','Luxembourg',1,130),
  ('MO','Macao',1,131),
  ('MG','Madagascar',1,132),
  ('MW','Malawi',1,133),
  ('MY','Malaysia',1,134),
  ('MV','Maldives',1,135),
  ('ML','Mali',1,136),
  ('MT','Malta',1,137),
  ('MH','Marshall Islands',1,138),
  ('MQ','Martinique',1,139),
  ('MR','Mauritania',1,140),
  ('MU','Mauritius',1,141),
  ('YT','Mayotte',1,142),
  ('MX','Mexico',1,143),
  ('FM','Micronesia, Federated States of',1,144),
  ('MD','Moldova, Republic of',1,145),
  ('MC','Monaco',1,146),
  ('MN','Mongolia',1,147),
  ('ME','Montenegro',1,148),
  ('MS','Montserrat',1,149),
  ('MA','Morocco',1,150),
  ('MZ','Mozambique',1,151),
  ('MM','Myanmar',1,152),
  ('NA','Namibia',1,153),
  ('NR','Nauru',1,154),
  ('NP','Nepal',1,155),
  ('NL','Netherlands',1,156),
  ('NC','New Caledonia',1,157),
  ('NZ','New Zealand',1,158),
  ('NI','Nicaragua',1,159),
  ('NE','Niger',1,160),
  ('NG','Nigeria',1,161),
  ('NU','Niue',1,162),
  ('NF','Norfolk Island',1,163),
  ('MK','North Macedonia',1,164),
  ('MP','Northern Mariana Islands',1,165),
  ('NO','Norway',1,166),
  ('OM','Oman',1,167),
  ('PK','Pakistan',1,168),
  ('PW','Palau',1,169),
  ('PS','Palestine, State of',1,170),
  ('PA','Panama',1,171),
  ('PG','Papua New Guinea',1,172),
  ('PY','Paraguay',1,173),
  ('PE','Peru',1,174),
  ('PH','Philippines',1,175),
  ('PN','Pitcairn',1,176),
  ('PL','Poland',1,177),
  ('PT','Portugal',1,178),
  ('PR','Puerto Rico',1,179),
  ('QA','Qatar',1,180),
  ('RO','Romania',1,181),
  ('RU','Russian Federation',1,182),
  ('RW','Rwanda',1,183),
  ('RE','Réunion',1,184),
  ('BL','Saint Barthélemy',1,185),
  ('SH','Saint Helena, Ascension and Tristan da Cunha',1,186),
  ('KN','Saint Kitts and Nevis',1,187),
  ('LC','Saint Lucia',1,188),
  ('MF','Saint Martin (French part)',1,189),
  ('PM','Saint Pierre and Miquelon',1,190),
  ('VC','Saint Vincent and the Grenadines',1,191),
  ('WS','Samoa',1,192),
  ('SM','San Marino',1,193),
  ('ST','Sao Tome and Principe',1,194),
  ('SA','Saudi Arabia',1,195),
  ('SN','Senegal',1,196),
  ('RS','Serbia',1,197),
  ('SC','Seychelles',1,198),
  ('SL','Sierra Leone',1,199),
  ('SG','Singapore',1,200)
ON DUPLICATE KEY UPDATE name=VALUES(name), is_active=VALUES(is_active), sort_order=VALUES(sort_order);
INSERT INTO countries (iso2,name,is_active,sort_order) VALUES
  ('SX','Sint Maarten (Dutch part)',1,201),
  ('SK','Slovakia',1,202),
  ('SI','Slovenia',1,203),
  ('SB','Solomon Islands',1,204),
  ('SO','Somalia',1,205),
  ('ZA','South Africa',1,206),
  ('GS','South Georgia and the South Sandwich Islands',1,207),
  ('SS','South Sudan',1,208),
  ('ES','Spain',1,209),
  ('LK','Sri Lanka',1,210),
  ('SD','Sudan',1,211),
  ('SR','Suriname',1,212),
  ('SJ','Svalbard and Jan Mayen',1,213),
  ('SE','Sweden',1,214),
  ('CH','Switzerland',1,215),
  ('SY','Syrian Arab Republic',1,216),
  ('TW','Taiwan, Province of China',1,217),
  ('TJ','Tajikistan',1,218),
  ('TZ','Tanzania, United Republic of',1,219),
  ('TH','Thailand',1,220),
  ('TL','Timor-Leste',1,221),
  ('TG','Togo',1,222),
  ('TK','Tokelau',1,223),
  ('TO','Tonga',1,224),
  ('TT','Trinidad and Tobago',1,225),
  ('TN','Tunisia',1,226),
  ('TR','Turkey',1,227),
  ('TM','Turkmenistan',1,228),
  ('TC','Turks and Caicos Islands',1,229),
  ('TV','Tuvalu',1,230),
  ('UG','Uganda',1,231),
  ('UA','Ukraine',1,232),
  ('AE','United Arab Emirates',1,233),
  ('GB','United Kingdom',1,234),
  ('US','United States',1,235),
  ('UM','United States Minor Outlying Islands',1,236),
  ('UY','Uruguay',1,237),
  ('UZ','Uzbekistan',1,238),
  ('VU','Vanuatu',1,239),
  ('VE','Venezuela, Bolivarian Republic of',1,240),
  ('VN','Viet Nam',1,241),
  ('VG','Virgin Islands, British',1,242),
  ('VI','Virgin Islands, U.S.',1,243),
  ('WF','Wallis and Futuna',1,244),
  ('EH','Western Sahara',1,245),
  ('YE','Yemen',1,246),
  ('ZM','Zambia',1,247),
  ('ZW','Zimbabwe',1,248),
  ('AX','Åland Islands',1,249)
ON DUPLICATE KEY UPDATE name=VALUES(name), is_active=VALUES(is_active), sort_order=VALUES(sort_order);

-- Seed a few default packages (Admin can edit/add/delete later)
INSERT INTO packages (name, is_active, sort_order) VALUES
('Diamond Sponsor',1,1),
('Platinum Sponsor',1,2),
('Gold Sponsor',1,3),
('Silver Sponsor',1,4),
('Exhibitor Only',1,5)
ON DUPLICATE KEY UPDATE is_active=VALUES(is_active), sort_order=VALUES(sort_order);

-- Seed default lost categories (Admin can edit later)
INSERT INTO lost_categories (name, is_active, sort_order) VALUES
('Price',1,1),
('Timing',1,2),
('No Budget',1,3),
('Competitor',1,4),
('No Response',1,5)
ON DUPLICATE KEY UPDATE is_active=VALUES(is_active), sort_order=VALUES(sort_order);

-- Seed default event placeholder
INSERT INTO events (name, is_active, sort_order) VALUES
('General',1,1)
ON DUPLICATE KEY UPDATE is_active=VALUES(is_active), sort_order=VALUES(sort_order);


CREATE TABLE IF NOT EXISTS job_runs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  job_name VARCHAR(80) NOT NULL,
  started_at TIMESTAMP NULL,
  finished_at TIMESTAMP NULL,
  status ENUM('running','success','failed') NOT NULL DEFAULT 'running',
  message VARCHAR(255) NULL,
  INDEX idx_job_name (job_name),
  INDEX idx_finished_at (finished_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
