services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: smartvisioncrm
      MYSQL_USER: sv
      MYSQL_PASSWORD: svpass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    command: ["--default-authentication-plugin=mysql_native_password","--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci"]
    volumes:
      - sv_mysql:/var/lib/mysql

volumes:
  sv_mysql:
